datafold/helm-charts

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/dfshell/values.yaml, charts/datafold/values.yaml, dev/config.yaml
=> [CX-2105]: Resolving issues with scratch build

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/datadog/Chart.yaml, charts/datafold/charts/datadog/README.md, charts/datafold/charts/datadog/templates/_helpers.tpl, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/datadog/templates/service.yaml, charts/datafold/charts/datadog/values.yaml, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/postgres/templates/_helpers.tpl, charts/datafold/charts/postgres/templates/statefulset.yaml, charts/datafold/charts/redis/templates/_helpers.tpl, charts/datafold/charts/redis/templates/statefulset.yaml, charts/datafold/charts/redis/values.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/server/templates/_helpers.tpl, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/worker/templates/_helpers.tpl, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/templates/_datadog.tpl, charts/datafold/templates/_env.tpl, charts/datafold/templates/_server.tpl, charts/datafold/templates/configmap.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml, dev/config.yaml, dev/secrets.yaml
=> [CX-2078]: Optionally deploy datadog in the cluster

charts/datafold/Chart.yaml, charts/datafold/charts/operator/values.yaml, charts/datafold/charts/postgres/Chart.yaml, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/values.yaml, dev/infra.yaml, dev/secrets.yaml
=> [CX-2035]: Fitting helm charts for rollout structure

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/deployment.yaml, charts/datafold/charts/redis/templates/statefulset.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/charts/worker_catalog/templates/deployment.yaml, charts/datafold/charts/worker_interactive/templates/deployment.yaml, charts/datafold/charts/worker_singletons/templates/deployment.yaml
=> [CX-2193]: Add liveness probes for all containers

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/charts/dfshell/values.yaml, charts/datafold/charts/nginx/values.yaml, charts/datafold/charts/operator/values.yaml, charts/datafold/charts/postgres/values.yaml, charts/datafold/charts/redis/values.yaml, charts/datafold/charts/scheduler/values.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/worker/values.yaml, charts/datafold/charts/worker_catalog/values.yaml, charts/datafold/charts/worker_interactive/values.yaml, charts/datafold/charts/worker_singletons/values.yaml
=> [CX-2194]: Set resource requests and limits

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/charts/dfshell/values.yaml, charts/datafold/charts/nginx/values.yaml, charts/datafold/charts/postgres/values.yaml, charts/datafold/charts/redis/values.yaml, charts/datafold/charts/scheduler/values.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/worker/values.yaml, charts/datafold/charts/worker_catalog/values.yaml, charts/datafold/charts/worker_interactive/values.yaml, charts/datafold/charts/worker_singletons/values.yaml
=> [CX-2192]: Apply security settings

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/_helpers.tpl, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/dfshell/templates/_helpers.tpl, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/redis/templates/_helpers.tpl, charts/datafold/charts/scheduler/templates/_helpers.tpl, charts/datafold/charts/server/templates/_helpers.tpl, charts/datafold/charts/worker/templates/_helpers.tpl, charts/datafold/charts/worker_catalog/templates/_helpers.tpl, charts/datafold/charts/worker_interactive/templates/_helpers.tpl, charts/datafold/charts/worker_singletons/templates/_helpers.tpl, charts/datafold/templates/_helpers.tpl, charts/datafold/templates/configmap.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
=> [CX-2269]: Ensure datadog works

charts/datafold/Chart.yaml, charts/datafold/charts/initjob/templates/job.yaml, charts/datafold/templates/_env.tpl
=> Gerard cx 2233 apply features mailserver on helm charts

charts/datafold/Chart.yaml, charts/datafold/charts/initjob/templates/job.yaml, charts/datafold/charts/nginx/templates/config-map.yaml, charts/datafold/templates/df_app_manager.yaml
=> [CX-2260]: Fix issues with version management

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/values.yaml
=> [CX-2042]: Remove memory limit for clickhouse

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/charts/nginx/templates/aws_targetgroupbinding.yaml
=> [CX-2042]: Migrate internal environments

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> [CX-2351]: Add clickhouse metrics

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/templates/_helpers.tpl, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/scheduler/templates/_helpers.tpl, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/server/templates/_helpers.tpl, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/worker/templates/_helpers.tpl, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/charts/worker_catalog/templates/_helpers.tpl, charts/datafold/charts/worker_catalog/templates/deployment.yaml, charts/datafold/charts/worker_interactive/templates/_helpers.tpl, charts/datafold/charts/worker_interactive/templates/deployment.yaml, charts/datafold/charts/worker_singletons/templates/_helpers.tpl, charts/datafold/charts/worker_singletons/templates/deployment.yaml
=> [CX-2345]: Better strategy for upgrades

charts/datafold/Chart.yaml, charts/datafold/charts/operator/templates/_helpers.tpl, charts/datafold/charts/operator/templates/deployment.yaml, charts/datafold/charts/operator/values.yaml
=> [CX-2355]: Add datadog monitoring

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/templates/_helpers.tpl, charts/datafold/charts/operator/templates/_helpers.tpl, charts/datafold/charts/operator/templates/deployment.yaml, charts/datafold/charts/scheduler/templates/_helpers.tpl, charts/datafold/charts/server/templates/_helpers.tpl, charts/datafold/charts/worker/templates/_helpers.tpl, charts/datafold/charts/worker_catalog/templates/_helpers.tpl, charts/datafold/charts/worker_interactive/templates/_helpers.tpl, charts/datafold/charts/worker_singletons/templates/_helpers.tpl
=> [CX-2377]: Better build system and fixing multiline parsing

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/values.yaml
=> [CX-2294]: Set flag to false by default

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/datadog/values.yaml
=> [CX-2397]: Add OOM kill detector

charts/datafold/Chart.yaml, charts/datafold/templates/configmap.yaml, charts/datafold/values.yaml
=> [CX-2400]: Removing unused environment variables

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/deployment.yaml, charts/datafold/charts/nginx/values.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/scheduler/values.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/worker/values.yaml, charts/datafold/charts/worker_singletons/values.yaml
=> [CX-2419]: Add better values for termination grace period

charts/datafold/Chart.yaml, charts/datafold/charts/redis/templates/persistent-volume.yaml, charts/datafold/charts/redis/templates/pvc.yaml, charts/datafold/charts/redis/values.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/charts/worker_catalog/templates/deployment.yaml, charts/datafold/charts/worker_interactive/templates/deployment.yaml, charts/datafold/charts/worker_singletons/templates/deployment.yaml
=> [CX-2430]: Add redis volume

charts/datafold/Chart.yaml, charts/datafold/charts/worker_singletons/templates/deployment.yaml
=> [CX-2036]: Resolving issues during the first migration

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/_helpers.tpl
=> [CX-2465]: Render the LB IP correctly

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/values.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/worker/values.yaml, charts/datafold/values.yaml
=> [CX-2474]: Distribute memory in a better way

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/_helpers.tpl, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/datadog/values.yaml, charts/datafold/templates/_postgres.tpl, charts/datafold/values.yaml
=> [CX-2475]: Settings for datadog database monitoring

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/_helpers.tpl, charts/datafold/templates/configmap.yaml
=> [CX-2492]: Set correct tag for freshpaint

charts/datafold-crds/Chart.yaml, charts/datafold-crds/templates/dfappmanagers.yaml
=> [CX-2448]: Include override version into CRD

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> [CX-2551]: Ignore kube-system pods in logging and metrics

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> [CX-2552]: Fix OOM kill detecton on gcp

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/secrets.yaml, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/clickhouse/values.yaml
=> [CX-2559]: Fix clickhouse backups on google

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
=> [BOYSCOUT] update clickhouse version

charts/datafold/Chart.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/values.yaml
=> [CX-2474]: Increase server memory

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl, charts/datafold/charts/clickhouse/templates/xmlconfig.yaml, charts/datafold/charts/clickhouse/values.yaml
=> [CX-2621]: Increase grace period for clickhouse to 60

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl
=> [CX-2634]: Map the file explicitly instead of whole directory

charts/datafold/Chart.yaml
=> [CX-2634]: Auto scale down GCP

charts/datafold/Chart.yaml, charts/datafold/templates/pdb.yaml
=> [CX-2634]: gcp nodepool does not scale down

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
=> [CX-2759]: Upgrade clickhouse

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> feat: Add support for more workers for large installs

charts/datafold/Chart.yaml, charts/datafold/templates/_env.tpl, charts/datafold/templates/configmap.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
Adds SaaS secrets and specific env vars not available in other deployments.
=> [CX-2609]: Add custom vars and secrets capability

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
=> [CX-3091]: Suppress processors profile log

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/persistent-volume.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/values.yaml
Added variables to specify a different file format for clickhouse data and logs.
=> Fix: Allow clickhouse data and logs volumes to have different file systems

charts/datafold/Chart.yaml, charts/datafold/templates/redis_pdb.yaml
=> [CX-3176]: add PDB for redis

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/charts/worker/templates/deployment.yaml
=> [P-2730][P-2359]: Clean up init container and health check fix

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
Updates version for clickhouse image.
=> fix: Update image version for clickhouse

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/config-map.yaml
=> fix: Hide server banner

charts/datafold/Chart.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/values.yaml
=> fix: Recalibrate number of web workers

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/Chart.yaml, charts/datafold/charts/nginx/templates/config-map.yaml
- update nginx chart with configuration to handle proxying datadog front end data 
=> [P-2773]: Nginx Updates for Datadog Proxy

charts/datafold/Chart.yaml, charts/datafold/charts/redis/values.yaml
=> fix: Add inter pod affinity for redis with clickhouse

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: By default, do not deploy the init job

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/config-map.yaml
=> fix: Set gzip types to js is also compressed

charts/datafold/Chart.yaml, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
=> fix: Replace intercom with pylon

charts/datafold/Chart.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/values.yaml
=> fix: Adjust memory and web worker count

charts/datafold/Chart.yaml, charts/datafold/templates/configmap.yaml, charts/datafold/values.yaml
Adds rate limit configuration for certain heavy load endpoints.
=> fix: Rate limit certain high load endpoints

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
Adds toleration to datadog to allow it to run on clickhouse specific nodes.
=> fix: Apply taint to datadog to allow it to run on ch node too

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
As part of incident 222 we have to update clickhouse to a new version as we changed a config in the `query_log` table.
This is not urgent to deploy to customers as they will have a much lower load than us
=> update: clickhouse version

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> [P-3007]: Increase memory to 1G

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: worker memory needs to use string

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl, charts/datafold/charts/clickhouse/templates/configmap.yaml, charts/datafold/charts/clickhouse/templates/secrets.yaml, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/clickhouse/values.yaml
Extend support for clickhouse backups to Azure.
=> feat: Enable clickhouse backups

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/_helpers.tpl, charts/datafold/charts/operator/templates/deployment.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
=> [P-2690]: Add new variables to helm charts

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/Chart.yaml
=> [BOYSCOUT] Update Clickhouse Tag to df12

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Do not override hostname setting

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> [P-2364]: Apply datafold namespace to datadog scope

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Add toleration for GPU enabled hosts

charts/datafold/Chart.yaml, charts/datafold/charts/operator/templates/deployment.yaml
=> fix: Set metrics host also for operator

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/logging_service.yaml, charts/datafold/templates/_datadog.tpl, charts/datafold/templates/_env.tpl
Fix Datadog logging by adding service that got removed in 0.6.30: https://github.com/datafold/helm-charts/commit/a7a2710534111d9e49d0a8aa6d71475d3e4c8997#diff-9050348eacb9e8b7c263315f2a37d0a164b95632e318b67540134f8022aa90ceL11
=> fix: Datadog logging

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/_helpers.tpl
=> [MON-4102]: Fix clickhouse db name in datadog metric collection

charts/datafold/Chart.yaml, charts/datafold/charts/worker/templates/_helpers.tpl, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/charts/worker/templates/pvc.yaml, charts/datafold/charts/worker/templates/storage_class.yaml, charts/datafold/charts/worker/values.yaml, charts/datafold/values.yaml
=> feat: Add scratch volumes for localstorage worker

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/clickhouse/values.yaml
=> [P-3333]: Add clickhouse service account back

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/serviceaccount.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/datadog/values.yaml
=> fix: Add option network performance monitoring for datadog

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Add custom tolerations for datadog

charts/datafold/Chart.yaml, charts/datafold/charts/operator/templates/role.yaml
=> [APP-4240]: Add permission for statefulsets too

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/storage_class.yaml
=> fix: Deploy correct storage class for gcp

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/storage_class.yaml
=> fix: Deploy storage class for azure

charts/datafold/Chart.yaml, charts/datafold/charts/operator/templates/deployment.yaml, charts/datafold/charts/operator/values.yaml
=> fix: update versions for operator

charts/datafold/Chart.yaml, charts/datafold/templates/configmap.yaml, charts/datafold/values.yaml
=> feat: [APP-4483] Add PORTAL_CERT_DATA to configmap

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/statefulset.yaml
=> fix: Apply updateStrategy for statefulsets

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml, charts/datafold/charts/datadog/values.yaml
=> fix: Ensure AWS EKS has a cluster name

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Set default tmgPS for storage worker to 1800

charts/datafold/Chart.yaml, charts/datafold/values.yaml
`terminationGracePeriodSeconds: "18000"`
=> Set default 5h grace period for storage worker

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Set better sizing for certain workers

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Don't pick up monitor tasks with regular workers

charts/datafold/Chart.yaml, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/worker/templates/deployment.yaml
=> fix: Add component name as env var to containers

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/values.yaml
=> fix: Increase memory for dfshell

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Recalibrate interactive workers

charts/datafold/Chart.yaml, charts/datafold/templates/configmap.yaml, charts/datafold/values.yaml
=> fix: Set variables to indicate storage worker deployment

charts/datafold-ephemeral/Chart.yaml, charts/datafold-ephemeral/templates/ephemeral.yaml, charts/datafold-ephemeral/values.yaml, charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/initjob/templates/job.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/storage-worker/templates/statefulset.yaml, charts/datafold/charts/worker-portal/templates/deployment.yaml, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/values.yaml
=> feat: add datafold ephemeral template

charts/datafold/Chart.yaml, charts/datafold/charts/dfshell/templates/_helpers.tpl, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/charts/dfshell/templates/serviceaccount.yaml, charts/datafold/charts/dfshell/values.yaml, charts/datafold/charts/operator/templates/_helpers.tpl, charts/datafold/charts/operator/templates/cluster_role_binding.yaml, charts/datafold/charts/operator/templates/deployment.yaml, charts/datafold/charts/operator/templates/role_binding.yaml, charts/datafold/charts/operator/templates/serviceaccount.yaml, charts/datafold/charts/operator/values.yaml, charts/datafold/charts/scheduler/templates/deployment.yaml, charts/datafold/charts/scheduler/templates/serviceaccount.yaml, charts/datafold/charts/scheduler/values.yaml, charts/datafold/charts/server/templates/_helpers.tpl, charts/datafold/charts/server/templates/deployment.yaml, charts/datafold/charts/server/templates/serviceaccount.yaml, charts/datafold/charts/server/values.yaml, charts/datafold/charts/storage-worker/templates/serviceaccount.yaml, charts/datafold/charts/storage-worker/templates/statefulset.yaml, charts/datafold/charts/storage-worker/values.yaml, charts/datafold/charts/worker-portal/templates/_helpers.tpl, charts/datafold/charts/worker-portal/templates/deployment.yaml, charts/datafold/charts/worker-portal/templates/serviceaccount.yaml, charts/datafold/charts/worker-portal/values.yaml, charts/datafold/charts/worker/templates/deployment.yaml, charts/datafold/charts/worker/templates/serviceaccount.yaml, charts/datafold/charts/worker/values.yaml
=> feat: add deployment service accounts

charts/datafold/Chart.yaml, charts/datafold/templates/_env.tpl, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
=> fix: Add RO database user

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/deployment.yaml, charts/datafold/values.yaml
=> fix: Use deployment for storage-worker

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Use hostNetwork for datadog daemonset

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/_helpers.tpl, charts/datafold/charts/datadog/templates/rbac.yaml, charts/datafold/charts/datadog/values.yaml, charts/datafold/charts/dfshell/templates/deployment.yaml, charts/datafold/templates/_datadog.tpl, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
Datadog agent can now monitor postgres from the cluster, relying less on the integrations.
=> fix: Let datadog monitor postgres

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/config-map.yaml
=> [ENG-831] Add ws support and upgrade for nginx config

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Add temporal observability

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/deployment.yaml
=> fix: Add storage-worker upgrade maxSurge vs maxUnavailable

charts/datafold/Chart.yaml, charts/datafold/templates/_helpers.tpl
=> fix: Fixes overriding the storage class

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Fixes temporal default namespace

charts/datafold/Chart.yaml, charts/datafold/values.yaml
=> fix: Increase terminationGracePeriodSeconds for lineage worker

charts/datafold/Chart.yaml, charts/datafold/charts/clickhouse/templates/configmap.yaml, charts/datafold/charts/clickhouse/templates/persistent-volume.yaml, charts/datafold/charts/clickhouse/templates/secrets.yaml, charts/datafold/charts/clickhouse/templates/serviceaccount.yaml, charts/datafold/charts/clickhouse/templates/statefulset.yaml, charts/datafold/charts/clickhouse/values.yaml, charts/datafold/charts/redis/templates/persistent-volume.yaml, charts/datafold/templates/_helpers.tpl, charts/datafold/templates/storageclass.yaml
=> fix: Several azure fixes

charts/datafold/Chart.yaml, charts/datafold/charts/storage-worker/templates/storage_class.yaml
Based on kubernetes StorageClass [schema definition](https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#), the `reclaim_policy` should be `reclaimPolicy`
=> Fix StorageClass reclaimPolicy

charts/datafold/Chart.yaml, charts/datafold/charts/datadog/templates/datadog_operator.yaml
=> fix: Add dmadocs namespace for datadog ingestion

.github/workflows/jeeves-check.yaml, .github/workflows/kubeconform.yaml, .github/workflows/lint.yaml, LICENSE, README.md, charts/datafold/Chart.yaml, dev/README.md, dev/config.yaml, dev/infra-aws.yaml, dev/infra-azure.yaml, dev/infra-gcp.yaml, dev/infra-local.yaml, dev/infra.yaml, dev/secrets.yaml, jeeves/README.md, jeeves/dev.py
=> ci: Add kubeconform validator

charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/_helpers.tpl, charts/datafold/charts/nginx/templates/ingress.yaml
=> fix: Fixes ingress deployment

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml
=> fix: Update crds for the operator

charts/datafold/Chart.yaml, charts/datafold/charts/operator/values.yaml
=> [ENG-1731]: Update versions

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/_helpers.tpl
=> fix: Remove part-of datafold annotation for DMA

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml, charts/datafold-manager/templates/rbac.yaml, charts/datafold/Chart.yaml, charts/datafold/charts/nginx/templates/_helpers.tpl, charts/datafold/charts/nginx/values.yaml
=> fix: Multiple domains on same LB

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml, charts/datafold/Chart.yaml, charts/datafold/charts/kept/Chart.yaml, charts/datafold/charts/kept/templates/_helpers.tpl, charts/datafold/charts/kept/templates/pvc.yaml, charts/datafold/charts/kept/templates/service.yaml, charts/datafold/charts/kept/templates/statefulset.yaml, charts/datafold/charts/kept/values.yaml, charts/datafold/templates/_kept.tpl, charts/datafold/values.yaml
=> feat: Added new kept server to deployment

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml
=> fix: New CRD for operator

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/statefulset.yaml, charts/datafold/templates/secrets.yaml, charts/datafold/values.yaml
=> fix: Add datafold docs auth key

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/statefulset.yaml, charts/datafold/charts/dma/values.yaml
=> fix: Use bedrock for DMA

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/statefulset.yaml
=> fix: Bedrock configuration

charts/datafold/Chart.yaml, charts/datafold/charts/dma/values.yaml
=> fix: spelling error

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/statefulset.yaml, charts/datafold/templates/secrets.yaml
=> fix: Remove claude env var

charts/datafold/Chart.yaml, charts/datafold/charts/dma/templates/statefulset.yaml, charts/datafold/templates/secrets.yaml
=> fix: Remove claude key, restore docs key

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: Fix version for now

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: Bump version

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: Update versions

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml
=> fix: CRD for operator

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml
=> fix: config crd

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: upgrade to latest operator

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: update operator

charts/datafold-manager/Chart.yaml, charts/datafold-manager/values.yaml
=> fix: Update version

charts/datafold-manager/Chart.yaml, charts/datafold-manager/templates/crds.yaml
=> fix: Fix the required fields

charts/datafold/Chart.yaml, charts/datafold/charts/dma/values.yaml
=> fix: Default limits for dma
